version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
      time: '00:00'
    open-pull-requests-limit: 10
    reviewers:
      - mpont91
    assignees:
      - mpont91
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope