#!/usr/bin/env bash

echo "🚀 Setting up your computer..."
echo "------------------------------"
echo
export DOTFILES_PATH="$HOME/.dotfiles"
echo "👉 Cloning into: '$DOTFILES_PATH'"

git --version 2>&1 >/dev/null
GIT_IS_AVAILABLE=$?


if [ $GIT_IS_AVAILABLE -ne 0 ]; then
        echo "Installing git first!"
        sudo apt -qq install git -y
fi

set -euo pipefail

git clone --depth 1 https://github.com/mpont91/dotfiles.git "$DOTFILES_PATH"

source "$DOTFILES_PATH/scripts/main.sh"
