name: CI-Mac

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: 🚀 Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-10.15
          - macos-11.0

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: bash scripts/mac-main.sh
